name: Release CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gruvbox-material.tdesktop-theme
          path: gruvbox-material.tdesktop-theme
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: gruvbox-material.tdesktop-theme
